### ISSUE TITLE
multiple function aligment

### ISSUE THREAD

**Issue by JCBurnside** [WarWithinMe/better-align#10]
I noticed that it doesn't recognize .func() for alignment for example:
taking this
```
return gulp.src(jsFiles)
    .pipe(plumber())
    .pipe(sourcemaps.init())
		    .pipe(concat('bundle.js'))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest('./content'));
```
and making it 
```
return gulp.src(jsFiles)
    .pipe(plumber())
    .pipe(sourcemaps.init())
    .pipe(concat('bundle.js'))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest('./content'));
```
I am not sure how difficult this would as I have never worked with the language you are using.

**Comment by WarWithinMe** [comment]
I'm sorry @JCBurnside , this is out of scope of this plugin. You need a code formatter / beautiful to achieve your goal.
