### ISSUE TITLE
Command 'wwm.aligncode' not found

### ISSUE THREAD

**Issue by vikas027** [WarWithinMe/better-align#11]
#### Environment
OSX: 10.11.2
VSCode: 1.16.1
Better Align: 1.1.10

#### Configuration
In `keybindings.json`
```json
{ "key": "cmd+2",  "command": "wwm.aligncode", "when": "editorTextFocus && !editorReadonly" },
```

#### Problem
![2017-09-16_12-53-17](https://user-images.githubusercontent.com/6998650/30508602-137187d2-9ade-11e7-9221-25656a033b38.png)

**Comment by WarWithinMe** [comment]
According to your last two issues, I assume you have installed different extension, but not better-align

**Comment by jaybong** [comment]
I had the same error, needed to reload VS Code.
