### ISSUE TITLE
Warning in toggle 'alignment.beforeSave'

### ISSUE THREAD

**Issue by vikas027** [WarWithinMe/better-align#12]
#### Environment
OSX: 10.11.2
VSCode: 1.16.1
Better Align: 1.1.10

#### Configuration
In `settings.json`
```json
"alignment.beforeSave": true
```

#### Problem
This works, but somehow shows incorrect boolean
![2017-09-16_13-08-46](https://user-images.githubusercontent.com/6998650/30508695-2fbd75c0-9ae0-11e7-9a8a-b7b20b5df8e1.png)

**Comment by WarWithinMe** [comment]
`alignment.beforeSave` is not an option of this extension
