### ISSUE TITLE
Align by Value?

### ISSUE THREAD

**Issue by bschlenk** [WarWithinMe/better-align#15]
Is there any way to make this align javascript objects by value instead of by colon? The plugin currently takes an object and does this:

```js
{
    a: 'a',
    asdf: 'sldfk',
    klj: 'lksjdlk',
}
```
=>
```js
{
    a   : 'a',
    asdf: 'sldfk',
    klj : 'lksjdlk',
}
```

But I would rather it keep the colon next to the key and align the vlaues, like this:

```js
{
    a:    'a',
    asdf: 'sldfk',
    klj:  'lksjdlk',
}
```

Is there a built in setting that would allow this to be configured?

**Comment by WarWithinMe** [comment]
try
```
alignment.surroundSpace : {
  "colon"      : [-1, 1], // The first number specify how much space to add to the left, can be negative.
                         // The second number is how much space to the right, can be negative.
}
```

**Comment by bschlenk** [comment]
Thanks, I see that there is even an example showing this in the readme. My bad.
