### ISSUE TITLE
Ternary statements in objects effected

### ISSUE THREAD

**Issue by dradickDT** [WarWithinMe/better-align#16]
`v 1.1.6`

I am having an issue where the colon of ternary statements are being effected as well when aligning properties of an object. Please see the screenshot below for the results of my values after using the align command.

<img width="783" alt="screen shot 2017-10-13 at 11 26 13 am" src="https://user-images.githubusercontent.com/30242594/31556545-1f635326-b00b-11e7-8aac-639e49c924b3.png">

The false values are pushed so far right because of longer property values set above the screenshot.

**Comment by WarWithinMe** [comment]
This plugin doesn't deal with language syntax, so it has no idea what is ternary operator.
In your case, I think you should use code formater / beautifier.
