### ISSUE TITLE
Can we add support for ' => ' ?

### ISSUE THREAD

**Issue by donsingh** [WarWithinMe/better-align#2]
I use php and when i need to align an array declaration:

```
$data = array(
    'text' => 'something',
    'here is another' => 'sample'
);
```

Gets converted to:

```
$data = array(
        'text'            = > 'something',
        'here is another' = > 'sample'
);
```

It does the alignment beautifully! But changes => to = > (space added) and breaks the code.

**Comment by WarWithinMe** [comment]
@donsingh Sure, will look into it.

**Comment by WarWithinMe** [comment]
@donsingh Implemented in v1.1.1. Try updating the extension. Let me know if there's any bugs ( Too lazy to test 🤣 )

**Comment by donsingh** [comment]
@WarWithinMe its working great at the moment... except you added `->`.
This is a problem because `->` is not an compute/assign operator but an access-relationship. 
We will never need to align -> because its always independent from other lines (such as the dot operator).
```
class->member;
anotherClass->amember;
sample->memz;
```

Will turn out:

```
class        -> member;
anotherClass -> amember;
sample       -> memz;
```
Which is ridiculous since those 3 lines are not related to each other and does not need to be aligned.
Here's what happens to my code:

FROM:
```
$data = array(
            'page_title' => 'No Title',
            'page_header' => 'CES',
            'page_description' => 'CES Data Summary',
            'footer_text' => $this->ces_model->activities(),
            'menu_index'  => 3.3,
);
```
TO:
```
$data = array(
            'page_title'       => 'No Title' ,
            'page_header'      => 'CES' ,
            'page_description' => 'CES Data Summary' ,
            'footer_text'      => $this              -> ces_model -> activities(),
            'menu_index'       => 3.3 ,
);
```

**tl-dr; drop the support for `->`. those things dont need to be aligned.**

**Comment by WarWithinMe** [comment]
@donsingh Totally forget `->` is commonly used as accessor. Will fix asap.

**Comment by WarWithinMe** [comment]
1efff89 should fix the issue

**Comment by donsingh** [comment]
Great work!
