### ISSUE TITLE
Bash not aligned properly

### ISSUE THREAD

**Issue by autoferrit** [WarWithinMe/better-align#3]
The current formatting rules will break bash scripts (sh, bash, zsh, etc)

## Start with
```bash
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_RUNTIME_DIR="$XDG_CACHE_HOME"
export ZPLUG_HOME="${HOME}/.zplug"
export ZSH_DIR="${XDG_CONFIG_HOME}/zsh"
```

## Expectation
```bash
export XDG_CONFIG_HOME="${HOME}/.config"
export  XDG_CACHE_HOME="${HOME}/.cache"
export   XDG_DATA_HOME="${HOME}/.local/share"
export XDG_RUNTIME_DIR="$XDG_CACHE_HOME"
export      ZPLUG_HOME="${HOME}/.zplug"
export         ZSH_DIR="${XDG_CONFIG_HOME}/zsh"
```

## Actual
```bash
export XDG_CONFIG_HOME = "${HOME}/.config"
export XDG_CACHE_HOME  = "${HOME}/.cache"
export XDG_DATA_HOME   = "${HOME}/.local/share"
export XDG_RUNTIME_DIR = "$XDG_CACHE_HOME"
export ZPLUG_HOME      = "${HOME}/.zplug"
export ZSH_DIR         = "${XDG_CONFIG_HOME}/zsh"
```

## Reason
Spaces around the `=` in most any shell script will break the assignment, alias, export, and others. They should be aligned on the `=` but have no spaces around them. Instead, the spaces should be inserted before the left hand side.

**Comment by WarWithinMe** [comment]
@autoferrit Currently this plugin doesn't distinguish language, so the behavior is generic.
It might take a while to implement the expected alignment. However, user will still need to change the config to enable the expected alignment.

**Comment by autoferrit** [comment]
I think if there was a per language config, or even just by extension that would be great. I think if you could have configs based on language, that would make the plugin even more invaluable. It already aligns better than most other plugins iv'e tried.

**Comment by WarWithinMe** [comment]
@autoferrit Vscode itself can configure different settings for different language. Now I just need to implement the new align logic and provide default settings for them.
If there's some other languages should be align in this way, please let me know.

**Comment by WarWithinMe** [comment]
@autoferrit

With better-align@1.1.3, it's possible to do the expected alignment, by changing surround space to `[-1, -1]`.
For example:
```
 "alignment.surroundSpace": {
    ...
    "assignment": [ -1, -1 ], 
    ...
 },
```

In order to only use this behavior in shellscript. You need to add language-specific settings in settings.json:
```
{
  ...
  ...
  "alignment.surroundSpace": {
    "colon": [ 1, 1 ],
    "assignment": [ 1, 1 ],
    "arrow":[ 1, 1 ],
    "comment": 2
  },

  "[shellscript]": {
    "alignment.surroundSpace": {
        "colon": [ 0, 1 ],
        "assignment": [ -1, -1 ],
        "arrow":[ 1, 1 ],
        "comment": 2
    }
  }
}
```

**Comment by autoferrit** [comment]
Awesome! This works great but there is only one minor issue. When a variable is assigned a url, it breaks

```bash
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_RUNTIME_DIR="$XDG_CACHE_HOME"
export ZPLUG_HOME="${HOME}/.zplug"
export ZSH_DIR="${XDG_CONFIG_HOME}/zsh"
export SOME_URL=http://google.com
```

is formatted to:
```bash
export XDG_CONFIG_HOME="${HOME}/.config"
export  XDG_CACHE_HOME="${HOME}/.cache"
export   XDG_DATA_HOME="${HOME}/.local/share"
export XDG_RUNTIME_DIR="$XDG_CACHE_HOME"
export      ZPLUG_HOME="${HOME}/.zplug"
export         ZSH_DIR="${XDG_CONFIG_HOME}/zsh"
export        SOME_URL=http:                    //google.com
```

However, wrapping the url in quotes will not break it. And the formatting is ok. It is a work around and ok with me. but if others use it, it may break their scripts. I tried setting `colon: [-1, -1]` as well and did not work. But, if I change `comment` to -1 it works without the quotes. this means `//` is being parsed as quotes in bash scripts, and not the proper `#`. I think if that could be fixed, it would work great.

**Comment by WarWithinMe** [comment]
@autoferrit 
Quoted strings are always treated as a whole, and will not be modify by better-align.

Currently, only `//` and `/**/` are recognized as comment. There's no plan to support different comment syntax for different language.

I think `://` should not be treated as comment. And in next release, there will be config to control whether align trailing comment.

**Comment by WarWithinMe** [comment]
It seems like `comment : -1` is actually the config to not align trailing comment.
And with 1.1.4, `://` will no longer being parsed as comment.

**Comment by autoferrit** [comment]
Woot! awesome work! thanks. appreciate it.
