### ISSUE TITLE
Hi. I really value this great extension, thank you.

### ISSUE THREAD

**Issue by oldbasilbear** [WarWithinMe/better-align#7]
Can I align code which looks like this? or do you hope to add this to another release perhaps?

  detailView: boolean = true;
  selectedEmployee: EmployeeProfile;
  weekNo: number = 0;

**Comment by WarWithinMe** [comment]
@oldbasilbear For this example, what is the expected result after aligning?

**Comment by oldbasilbear** [comment]
Good point. I would like to see the following:

```
detailView              : boolean = true;
selectedEmployee : EmployeeProfile;
weekNo                  : number = 0;

```
I think perhaps that when there is an assignment on the line, the alignment struggles to decide what to do.

**Comment by WarWithinMe** [comment]
This plugin will look up and down to find identical lines to align. Lines are consider identical when they have the same operator (normally the first operator). However, when assignment is presented, the operator of the line is always assignment (Just a lazy way to determine which operator to be used when there're several ops in a line).

In your case, when caret is on the 1st line or 3rd line, it will look up and down to find more lines that has assignment operator. And when caret is on the 2nd line, it will find lines with colon

I think I can improve the algorithm of finding the best op to be aligned. Then your example can be aligned.

**Comment by oldbasilbear** [comment]
Thanks for taking the time to consider that. I look forward to that improvement as and when it comes along. My colleagues and I do certainly make lots of use of this extension. Cheers.
