### ISSUE TITLE
如下代码不应该格式化吧？

### ISSUE THREAD

**Issue by kylezhang** [WarWithinMe/better-align#9]
- 如下代码不应该格式化吧？
![align](https://user-images.githubusercontent.com/3679798/27906051-8857452a-6274-11e7-894d-9dfeb6822d01.png)

- 这种没有达到效果
![wx20170706-180250](https://user-images.githubusercontent.com/3679798/27906270-726e1364-6275-11e7-9914-333124cdeccb.png)

**Comment by WarWithinMe** [comment]
前者是 feature， 主要是为了达到声明变量时对齐

```
var aaa = 1,
    bbb = 2,
    ccc = 3
```

因为不是语法层面的 format， 无法知道是不是在声明变量，所以类似的文本都会这样对齐。在这个例子里面其实应该在 const s 这一行后加入空行。 这样对齐下面的代码的时候就不会影响 const s 行。这个是正确的使用姿势。

后者大概是个 bug

**Comment by kylezhang** [comment]
so ga,
